FROM python:3.7

# add project
ADD ./code /app
WORKDIR /app

# install flask
RUN pip install --upgrade pip
RUN pip install Flask==1.0.2 requests line-bot-sdk PyMYSQL

# run flask
#ENTRYPOINT ["python"]
#CMD ["test_app.py"]

#RUN /bin/bash -c 'python test_app.py'

# run flask
ENTRYPOINT ["python"]
#CMD ["python app.py"]

