version: '3'
services:
  db:
    image: mariadb:10.1
    container_name: chatbot_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql_data:/var/lib/mysql
  jupyter:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-jupyter
    container_name: chatbot_jupyter
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
      - ./code:/home/jovyan/
    command: start.sh jupyter notebook --NotebookApp.token=''
  serveo:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-serveo
    container_name: chatbot_serveo
    tty: true
    stdin_open: true
    depends_on:
      - jupyter
    ports:
      - "4040:4040"
    command: autossh -M 0 -R chatbottest.serveo.net:80:chatbot_jupyter:5000 -o StrictHostKeyChecking=no serveo.net
